### ISSUE TITLE
Implement an ability to listen to B feed of snapshot channels

### ISSUE THREAD

**Issue by kolybelkin** [epam/java-cme-mdp3-handler#18]
According to variable `snptFeedToUse` from `com.epam.cme.mdp3.core.channel.MdpChannelImpl` now it is used only A feed and there is no an ability to change it automatically(for example: if there is no data from A feed) or manually.

**Comment by iamolever** [comment]
Minor requirements in fact. It's critical for platform to have A available, and options with both A and B will decrease performance.

**Comment by swarwick** [comment]
This was added in a recent update, you can now specify the snapshot channel to use in the builder.
