### ISSUE TITLE
Security Definitions info in not printed on console / log

### ISSUE THREAD

**Issue by TheMiracleExpress** [epam/java-cme-mdp3-handler#39]
b2bits-jmdp3-2.0.1

===============

Start Java MDP on some CME AutoCert+ channel (9xx)
– Expected
 Information for all received securities should be printed on console and in log:

Received SecurityDefinition(d). securityID '{}', ChannelId: {}, Schema Id: {}, securityGroup '{}', marketSegmentID '{}', strikePrice '{}'

eventTime - '{}'({}), eventType - '{}'

 

– In fact:

There is no information about securities
Log and configs are attached (note, add TCP connection stub to channel you want to use)

[ConfigLog.zip](https://github.com/epam/java-cme-mdp3-handler/files/2159373/ConfigLog.zip)

**Comment by iamolever** [comment]
Fixed in PR https://github.com/epam/java-cme-mdp3-handler/pull/45

**Comment by kolybelkin** [comment]
PR #45 was merged into master. @TheMiracleExpress please check it and close the issue in case of success.

**Comment by iamolever** [comment]
Should be fixed and merged already
