### ISSUE TITLE
MetadataContainer should expose the SbeFieldType list

### ISSUE THREAD

**Issue by swarwick** [epam/java-cme-mdp3-handler#42]
The SbeGroupType[] is already exposed and the SbeFieldType[] should also be exposed so that third parties can use the already parsed xml metadata when processing messages.

Also the AbstractFieldSet should expose the MetadataContainer so when dealing with callbacks the end user can look into that metadata container for schema/type information.

I do not see any reason that these containers cannot be exposed to the end user.  If internal data needs to be protected then maybe lock down the set calls to package.

**Comment by iamolever** [comment]
Yes, I suppose you are right. Metadata should be available. I will review later. Thanks!
