### ISSUE TITLE
MDPOffHeapBuffer does not track duplicate entries causing extra memory usage

### ISSUE THREAD

**Issue by swarwick** [epam/java-cme-mdp3-handler#55]
Currently the MDPOffHeapBuffer does not track the MsgSeqNum for packets being added and if using both A and B channels this can cause a massive amount of duplicate values to be stored which is causing extra memory usage that could hold more actual messages vs duplicates. It also causes more CPU cycles when the buffer is finally replayed as half are duplicates.

**Comment by swarwick** [comment]
I would propose the class contains
`private LongHashSet msgSeqNums = new LongHashSet();`

The add method should be change to something like

>     @Override
>     public synchronized void add(MdpPacket entity) {
>     	if (!isPacketEmpty(entity) && msgSeqNums.contains(entity.getMsgSeqNum())) {
>     		return;
>     	}
>     	msgSeqNums.add(entity.getMsgSeqNum());
>         int firstEmptyPosition = calculateFirstEmptyPosition();
>         MdpPacket mdpPacket = data[firstEmptyPosition];        
>         copy(entity, mdpPacket);
>         sort();
>     }

And then in the remove method we just check and also remove from the LongHashSet 

>     @Override
>     public synchronized MdpPacket remove() {
>         MdpPacket nextPackage = data[0];
>         if(isPacketEmpty(nextPackage)){
>             return null;
>         }
>         copy(nextPackage, resultPacket);
>         copy(emptyPacket, nextPackage);
>         System.arraycopy(data, 1, data, 0, data.length - 1);
>         data[data.length - 1] = nextPackage;
>         full = false;
>         msgSeqNums.remove(resultPacket.getMsgSeqNum());
>         return resultPacket;
>     }

**Comment by swarwick** [comment]
Note this does have a minor performance hit for the hash but also reduces some performance hit because of the extra memory copies and sorting that would occur with duplicate entries.

**Comment by swarwick** [comment]
I submitted a pull request to fix this.

**Comment by iamolever** [comment]
As for me I don't like calculateFirstEmptyPosition() logic. It's cycle.
        for (int i = 0; i < data.length; i++) {
            MdpPacket nextPackage = data[i];
            if(isPacketEmpty(nextPackage)){
                return i;
            }
        }

Should be always look for data slot from the beginning?

**Comment by iamolever** [comment]
Moreover as I see we have ordered data:

    public synchronized void add(MdpPacket entity) {
        int firstEmptyPosition = calculateFirstEmptyPosition();
        MdpPacket mdpPacket = data[firstEmptyPosition];
        copy(entity, mdpPacket);
        sort();
    }

I suppose logic of container should be ready to handle duplicates in moment of inserting.

**Comment by swarwick** [comment]
Sorry I dont follow, what do those comments have to do with handling duplicates? it seems like comments on exiting code that I did not touch, that should probably be handled in another issue?

**Comment by iamolever** [comment]
> Sorry I dont follow, what do those comments have to do with handling duplicates? it seems like comments on exiting code that I did not touch, that should probably be handled in another issue?

Yes, your code is correct. I'm thinking about entire class logic, and probably with another implementation the duplicate issue must be not exist too.

**Comment by iamolever** [comment]
@kolybelkin, could you explain the code above?
